#! /usr/bin/env bash

D=$(dirname "$BASH_SOURCE"); cd "$D"

rm -rf A.class
X=0
"$INSTALL/openjml" --rac --rac-check-assumptions A.java
"$INSTALL/openjml-java" A | diff out1.txt - || X=1

"$INSTALL/openjml" --rac --no-rac-check-assumptions A.java
"$INSTALL/openjml-java" A | diff out2.txt - || X=1

rm -rf A.class
exit $X
