#! /usr/bin/env bash

D=$(dirname "$BASH_SOURCE"); cd "$D"

rm -rf A.class
X=0
"$INSTALL/openjml" --rac --rac-compile-to-java-assert A.java
"$INSTALL/openjml-java" -ea A 2>&1 | diff out1.txt - || X=1

"$INSTALL/openjml" --rac --no-rac-compile-to-java-assert A.java
"$INSTALL/openjml-java" A 2>&1 | diff out2.txt - || X=1

rm -rf A.class
exit $X
