#! /usr/bin/env bash

D=$(dirname "$BASH_SOURCE"); cd "$D"

rm -rf A.class 
X=0
"$INSTALL/openjml" --rac A.java

"$INSTALL/openjml-java" A 2>&1 | diff out1.txt - || X=1

"$INSTALL/openjml-java" -Dorg.jmlspecs.openjml.rac=stdout A 2>&1 | diff out1.txt - || X=1

"$INSTALL/openjml-java" -Dorg.jmlspecs.openjml.rac=showstack A >& actual ; ( diff out1a.txt actual  ) || X=1

##"$INSTALL/openjml-java" -Dorg.jmlspecs.openjml.rac=exception A >& actual ; ( sed -e 's/\$\\\$\$/$/' out2.txt | diff - actual  ) || X=1
"$INSTALL/openjml-java" -Dorg.jmlspecs.openjml.rac=exception A >& actual ; ( diff out2.txt actual && rm -rf actual ) || X=1

"$INSTALL/openjml-java" -esa -Dorg.jmlspecs.openjml.rac=javaassert A 2>&1 | diff out3.txt - || X=1

"$INSTALL/openjml-java" -Dorg.jmlspecs.openjml.rac=assertionerror A 2>&1 | diff out4.txt - || X=1

rm -rf A.class
exit $X
